import { describe, expect, it } from "vitest";
import * as XLSX from "xlsx";
import { assertSupportedWorkbookFile } from "../lib/data-mapper/excel-import/file-validation";
import { detectHeaderRow } from "../lib/data-mapper/excel-import/header-detection";
import { createWorkbookSummary } from "../lib/data-mapper/excel-import/workbook-summary";
import { createWorksheetPreview, previewRowLimit } from "../lib/data-mapper/excel-import/worksheet-reader";

function workbookFromRows(sheetName: string, rows: string[][]) {
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, XLSX.utils.aoa_to_sheet(rows), sheetName);
  return workbook;
}

describe("Excel import engine", () => {
  it("accepts supported Excel workbook extensions", () => {
    expect(() => assertSupportedWorkbookFile("pricebook.xlsx")).not.toThrow();
    expect(() => assertSupportedWorkbookFile("pricebook.xls")).not.toThrow();
    expect(() => assertSupportedWorkbookFile("pricebook.xlsm")).not.toThrow();
  });

  it("rejects unsupported file types with a friendly validation error", () => {
    expect(() => assertSupportedWorkbookFile("pricebook.csv")).toThrow("Upload an Excel workbook");
  });

  it("detects a header row below introductory worksheet text", () => {
    const result = detectHeaderRow([
      ["June pricebook import"],
      ["Generated by commercial operations"],
      ["SKU", "Product", "Partner", "Price"],
      ["A-001", "Router", "North", "120"]
    ]);

    expect(result.rowNumber).toBe(3);
    expect(result.headers).toEqual(["SKU", "Product", "Partner", "Price"]);
    expect(result.confidence).toBe("high");
  });

  it("summarises workbook and worksheet dimensions", () => {
    const workbook = workbookFromRows("Products", [
      ["SKU", "Product", "Price"],
      ["A-001", "Router", "120"],
      ["A-002", "Switch", "180"]
    ]);
    const summary = createWorkbookSummary(workbook, "june-pricebook.xlsx");

    expect(summary.workbookName).toBe("june-pricebook");
    expect(summary.worksheetCount).toBe(1);
    expect(summary.totalRows).toBe(3);
    expect(summary.totalColumns).toBe(3);
    expect(summary.worksheets[0]?.importStatus).toBe("Ready");
  });

  it("limits worksheet preview rows to the first 100 data rows", () => {
    const rows = [
      ["SKU", "Product"],
      ...Array.from({ length: 150 }, (_, index) => [`SKU-${index + 1}`, `Product ${index + 1}`])
    ];
    const workbook = workbookFromRows("Products", rows);
    const worksheet = workbook.Sheets.Products;
    const summary = createWorkbookSummary(workbook, "large-pricebook.xlsx").worksheets[0];

    expect(summary).toBeDefined();
    if (!summary) throw new Error("Expected worksheet summary");

    const preview = createWorksheetPreview("Products", worksheet, summary);
    expect(preview.rows).toHaveLength(previewRowLimit);
    expect(preview.rows[0]).toEqual(["SKU-1", "Product 1"]);
    expect(preview.rows[99]).toEqual(["SKU-100", "Product 100"]);
  });
});
