import { describe, expect, it, vi } from "vitest";
import ExcelJS from "exceljs";
import { assertSupportedWorkbookFile } from "../lib/data-mapper/excel-import/file-validation";
import { detectHeaderRow } from "../lib/data-mapper/excel-import/header-detection";
import { friendlyExcelImportMessage } from "../lib/data-mapper/excel-import/errors";
import { readWorkbook } from "../lib/data-mapper/excel-import/workbook-reader";
import { createWorkbookSummary } from "../lib/data-mapper/excel-import/workbook-summary";
import { createWorksheetPreview, previewRowLimit } from "../lib/data-mapper/excel-import/worksheet-reader";

function workbookFromRows(sheetName: string, rows: string[][]) {
  const workbook = new ExcelJS.Workbook();
  const worksheet = workbook.addWorksheet(sheetName);
  worksheet.addRows(rows);
  return workbook;
}

describe("Excel import engine", () => {
  it("accepts supported Excel workbook extensions", () => {
    expect(() => assertSupportedWorkbookFile("pricebook.xlsx")).not.toThrow();
    expect(() => assertSupportedWorkbookFile("pricebook.xlsm")).not.toThrow();
  });

  it("rejects legacy binary workbooks with a friendly message", () => {
    expect(() => assertSupportedWorkbookFile("pricebook.xls")).toThrow("Please open 'pricebook.xls' in Excel, save it as .xlsx or .xlsm");
  });

  it("rejects unsupported file types with a friendly validation error", () => {
    expect(() => assertSupportedWorkbookFile("pricebook.csv")).toThrow("The file 'pricebook.csv' is not a supported Excel workbook");
  });

  it("includes the filename in workbook read failure messages and logs the underlying error in development", async () => {
    vi.stubEnv("NODE_ENV", "development");
    const consoleError = vi.spyOn(console, "error").mockImplementation(() => undefined);

    try {
      await readWorkbook(new File([new Uint8Array([1, 2, 3, 4])], "broken-pricebook.xlsx"));
      throw new Error("Expected workbook read to fail");
    } catch (error) {
      expect(friendlyExcelImportMessage(error)).toBe(
        "The workbook 'broken-pricebook.xlsx' could not be read. It may be password protected, damaged, or saved in a format this importer cannot safely read. Please open the file in Excel, save it again as .xlsx, and try uploading the saved copy."
      );
      expect(consoleError).toHaveBeenCalledWith(
        "[Axiom Data Mapper] ExcelJS workbook read failed",
        expect.objectContaining({ fileName: "broken-pricebook.xlsx" })
      );
    } finally {
      consoleError.mockRestore();
      vi.unstubAllEnvs();
    }
  });

  it("detects a header row below introductory worksheet text", () => {
    const result = detectHeaderRow([
      ["June pricebook import"],
      ["Generated by commercial operations"],
      ["SKU", "Product", "Partner", "Price"],
      ["A-001", "Router", "North", "120"]
    ]);

    expect(result.rowNumber).toBe(3);
    expect(result.headers).toEqual(["SKU", "Product", "Partner", "Price"]);
    expect(result.confidence).toBe("high");
  });

  it("summarises workbook and worksheet dimensions", () => {
    const workbook = workbookFromRows("Products", [
      ["SKU", "Product", "Price"],
      ["A-001", "Router", "120"],
      ["A-002", "Switch", "180"]
    ]);
    const summary = createWorkbookSummary(workbook, "june-pricebook.xlsx");

    expect(summary.workbookName).toBe("june-pricebook");
    expect(summary.worksheetCount).toBe(1);
    expect(summary.totalRows).toBe(3);
    expect(summary.totalColumns).toBe(3);
    expect(summary.worksheets[0]?.importStatus).toBe("Ready");
  });

  it("limits worksheet preview rows to the first 100 data rows", () => {
    const rows = [
      ["SKU", "Product"],
      ...Array.from({ length: 150 }, (_, index) => [`SKU-${index + 1}`, `Product ${index + 1}`])
    ];
    const workbook = workbookFromRows("Products", rows);
    const worksheet = workbook.getWorksheet("Products");
    const summary = createWorkbookSummary(workbook, "large-pricebook.xlsx").worksheets[0];

    expect(summary).toBeDefined();
    if (!summary) throw new Error("Expected worksheet summary");
    if (!worksheet) throw new Error("Expected worksheet");

    const preview = createWorksheetPreview("Products", worksheet, summary);
    expect(preview.rows).toHaveLength(previewRowLimit);
    expect(preview.rows[0]).toEqual(["SKU-1", "Product 1"]);
    expect(preview.rows[99]).toEqual(["SKU-100", "Product 100"]);
  });
});
