"use server";
import { prisma } from "@/lib/prisma";
import { requireUser } from "@/lib/auth";
import { sendEmail } from "@/lib/email";
import { audit } from "@/lib/audit";
import { hasPermission } from "@/lib/permissions";
import { redirect } from "next/navigation";
import { escapeHtml } from "@/lib/html";
import { axiomDefaults } from "@/config/axiom-defaults";
export async function createSupportTicket(formData:FormData){ const user=await requireUser(); if(!hasPermission(user,"raiseSupportTickets")) return {error:"You do not have permission to raise support tickets."}; const title=String(formData.get("title")||"").trim(); const description=String(formData.get("description")||"").trim(); if(!title||!description) return {error:"Title and description are required."}; const ticket=await prisma.supportTicket.create({data:{tenantId:user.tenantId!,requesterId:user.id,requesterEmail:user.email,title,description,ticketType:String(formData.get("ticketType")||"Question"),affectedArea:String(formData.get("affectedArea")||"General")}}); await sendEmail({tenantId:user.tenantId,requestedById:user.id,to:process.env.SUPPORT_EMAIL||axiomDefaults.email.supportEmail,notificationType:"support",subject:`New support ticket: ${title}`,html:`<p>${escapeHtml(description)}</p>`}); await audit({tenantId:user.tenantId,userId:user.id,action:"SUPPORT_CREATED",entityType:"SupportTicket",entityId:ticket.id}); redirect("/support?submitted=1"); }
export async function createSecurityIssue(formData:FormData){ const user=await requireUser(); const description=String(formData.get("description")||"").trim(); if(!description) return {error:"Issue description is required."}; const issue=await prisma.securityIssue.create({data:{tenantId:user.tenantId!,userId:user.id,userEmail:user.email,pageUrl:String(formData.get("pageUrl")||""),description,severity:String(formData.get("severity")||"MEDIUM") as "LOW"|"MEDIUM"|"HIGH"|"CRITICAL"}}); await sendEmail({tenantId:user.tenantId,requestedById:user.id,to:process.env.SUPPORT_EMAIL||axiomDefaults.email.supportEmail,notificationType:"security_issue",subject:"Security issue reported",html:`<p>${escapeHtml(issue.description)}</p>`}); await audit({tenantId:user.tenantId,userId:user.id,action:"SECURITY_ISSUE_REPORTED",entityType:"SecurityIssue",entityId:issue.id}); redirect("/security-issue?submitted=1"); }
export async function createFeatureRequest(formData:FormData){ const user=await requireUser(); if(!hasPermission(user,"createRecords") && !hasPermission(user,"manageCustomerSettings")) return {error:"You do not have permission to submit feature requests."}; const request=await prisma.featureRequest.create({data:{tenantId:user.tenantId!,requesterId:user.id,title:String(formData.get("title")||""),requestType:String(formData.get("requestType")||"Feature idea"),businessReason:String(formData.get("businessReason")||""),benefit:String(formData.get("benefit")||""),affectedArea:String(formData.get("affectedArea")||"General")}}); return {success:`Feature request ${request.id} submitted.`}; }
